server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhoushichun/config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - config
#      ####读取分支
#      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#rabbitmq相关配置


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7004.com:7004/eureka
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"