server:
  port: 8002

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  application:
    name: cloud-provider-payment

#logging:
#  config: classpath:config/logback-spring.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type:
      field-strategy: not_null
      db-type: mysql
