server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8002         #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT #匹配后提供服务的路由地址
          predicates:
            - Path=/system/payment/listAll/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8002          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT #匹配后提供服务的路由地址
          predicates:
            - Path=/system/payment/listHystrix/**         # 断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7004.com:7004/eureka
